# Generated by Django 5.0.6 on 2024-06-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("synopsis", models.TextField()),
                ("poster", models.ImageField(upload_to="posters/")),
            ],
        ),
        migrations.CreateModel(
            name="BackstagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="backstages/")),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backstage_photos",
                        to="films.film",
                    ),
                ),
            ],
        ),
    ]
