# Generated by Django 5.0.6 on 2024-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
